GET http://localhost:1337/employees/1

###

POST http://localhost:1337/hiring-requests
Content-Type: application/json

{
    "firstName": "Dude",
    "lastName": "Skywalker",
    "homeEmail": "dskywalker@aol.com",
    "homePhone": "867-5309",
    "requestedDepartment": "DEV",
    "requiredSalary": 200000
}
